name: Mobile tab JS

on: [workflow_dispatch, push, pull_request]

env:
  HUSKY: 0

jobs:
  run:
    uses: flarum/framework/.github/workflows/REUSABLE_frontend.yml@2.x
    with:
      enable_bundlewatch: false
      enable_prettier: true
      enable_typescript: false

      frontend_directory: ./js
      backend_directory: .
      js_package_manager: npm
      main_git_branch: master
